[phases.setup]
nixPkgs = ["python310"]  # ✅ Only python310

[phases.build]
cmds = [
  "pip install --upgrade pip",  # Optional: to get latest pip
  "pip install -r requirements.txt",
  "python -m spacy download en_core_web_sm"
]

[start]
cmd = "python app.py"
